config/routes.rb
Rails.application.routes.draw do

  get 'homes/index'
  get 'search',to: "students#search"


  root "students#index"
  get "sections/index"
  get 'teachers/index'


  resources :students do
    collection do
      get 'search'
      get 'search1'

      # /students/search for searching students
    end
  end

    resources :sections do
      collection do
        get 'search'
      end
    end

  resources :teachers do
    collection do
      get 'search'
    end
  end
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :students
end

app/models/student.rb
	class Student < ApplicationRecord
	belongs_to :section	
end

app/models/teacher.rb
class Teacher < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index

  end
  end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all  
  end
  def search
    query = params[:query]
    @sections = Section.where("name LIKE ? OR student_range LIKE ? ",
                              "%#{query}%","%#{query}%")
  end

  def show
    # binding.pry
    @section = Section.find_by_id(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
      @section = Section.new( 
        name: params[:name],
        student_range: params[:student_range] 
             )
      if @section.save
        redirect_to (sections_index_path)
      else
        render('new')
      end    
    end

  def edit
    @section = Section.find_by_id(params[:id])
    @student = Student.last

  end

  def update
    # binding.pry
      @section = Section.find_by_id(params[:id])
      if @section.update(
        name: params[:section][:name],
        student_range: params[:section][:student_range], 
        )
        redirect_to @section
      else

        flash[:error] = "Section not found."
        render 'edit'
      end
    end
    def destroy
    @section = Section.find_by_id(params[:id])
    @section.destroy
    redirect_to (sections_index_path)
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])

  end

  def new
    @student = Student.new({:name => 'Enter your name', :father_name => 'Enter your Father Name '})
  end   

  def create
    @student = Student.new( 
    name: params[:student][:name],
    age: params[:student][:age], 
    father_name: params[:student][:father_name], 
    Phone_number: params[:student][:Phone_number],
    Email: params[:student][:Email],
    Blood_group: params[:student][:Blood_group],
    Created: params[:student][:Created],
    Updated: params[:student][:Updated]
    )
    if @student.save
      redirect_to student_index_path
    else
      render(new)
    end    
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @students = Student.all
  end
  def search1
      # app/controllers/students_controller.rb
          query = params[:query]
      @students = Student.where("name LIKE ? OR age = ? OR phone_number LIKE ?  OR gender LIKE ?  OR email LIKE ? OR date_of_birth LIKE ? OR blood_group LIKE ? ",
                                "%#{query}%", query.to_i, "%#{query}%","%#{query}%","%#{query}%","%#{query}%" ,"%#{query}%")

      @sections = Section.where("name LIKE ? OR student_range LIKE ? ",
                                "%#{query}%","%#{query}%")

      @teachers = Teacher.where("name LIKE ? OR phone_number LIKE ?  OR gender LIKE ?  OR email LIKE ? OR date_of_birth LIKE ?  OR address	 LIKE ? OR qualification LIKE ? OR subject LIKE ?",
                                "%#{query}%", "%#{query}%","%#{query}%","%#{query}%" ,"%#{query}%" ,"%#{query}%","%#{query}%","%#{query}%")
  end
  def search
    query = params[:query]
    @students = Student.where("name LIKE ? OR age = ? OR phone_number LIKE ?  OR gender LIKE ?  OR email LIKE ? OR date_of_birth LIKE ? OR blood_group LIKE ? ",
                              "%#{query}%", query.to_i, "%#{query}%","%#{query}%","%#{query}%","%#{query}%" ,"%#{query}%")
  end


  def show
    @student = Student.find_by_id(params[:id])
  end

  def new
    # binding.pry
    @student = Student.new
  end   


  def create
     # binding.pry
      @student = Student.new(
       #here name: is key and params is object params[:name] would retrun the value
        name: params[:name],
        age: params[:age],
        father_name: params[:father_name],
        phone_number: params[:phone_number],
          email: params[:email],
        guardian_no: params[:guardian_no],
        gender: params[:gender],
        date_of_birth: params[:date_of_birth],
        blood_group: params[:blood_group],
        section_id: params[:section_id]
       )

    if @student.save
      redirect_to (students_path)
    else
      render('new')
    end
  end

  def edit
    # binding.pry
    @student = Student.find_by_id(params[:id])
    # binding.pry
    # binding.pry
  end

  def update
    # binding.pry
    @student = Student.find_by_id(params[:id])

    if @student.update(
      name: params[:student][:name],
      age: params[:student][:age],
      father_name: params[:student][:father_name],
      phone_number: params[:student][:phone_number],
      email: params[:student][:email],
      guardian_no: params[:student][:guardian_no],
      date_of_birth: params[:student][:date_of_birth],
      gender: params[:student][:gender],
      blood_group: params[:student][:blood_group],
      section_id: params[:student][:section_id],
    )
      redirect_to @student
      # binding.pry
    else
      # binding.pry
      flash[:error] = "Student not found."
      render 'show'
    end
  end

  def destroy
    @student = Student.find_by_id(params[:id])
    @student.destroy
    redirect_to (students_path)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end
  def search
    query = params[:query]

    @teachers = Teacher.where("name LIKE ? OR phone_number LIKE ?  OR gender LIKE ?  OR email LIKE ? OR date_of_birth LIKE ?  OR address	 LIKE ? OR qualification LIKE ? OR subject LIKE ?",
                              "%#{query}%", "%#{query}%","%#{query}%","%#{query}%" ,"%#{query}%" ,"%#{query}%","%#{query}%","%#{query}%")
  end
  
  def show
    @teacher = Teacher.find_by_id(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def edit
    @teacher = Teacher.find_by_id(params[:id])
  end
  

  
  def create

    @teacher  = Teacher.new( 
      name: params[:name],
      phone_number: params[:phone_number],
      email: params[:email],
      gender: params[ :gender],
      date_of_birth: params[ :date_of_birth],
      address: params[:address],
      qualification: params[:qualification],
      subject: params[:subject]
)
    @teacher.errors
    if @teacher.save
      redirect_to (teachers_index_path)
    else
      render('new')
    end    
  end

  def update
      @teacher = Teacher.find_by_id(params[:id])
    
    if @teacher.update( 
        name: params[:teacher][:name],
        phone_number: params[:teacher][:phone_number],
        email: params[:teacher][:email],
        gender: params[:teacher][ :gender],
        date_of_birth: params[:teacher][ :date_of_birth],
        address: params[:teacher][:address],
        qualification: params[:teacher][:qualification],
        subject: params[:teacher][:subject]
)
    redirect_to @teacher
    else
      flash[:error] = "Teacher not found."
      render 'edit'
    end

  end

  def destroy
    @teacher = Teacher.find_by_id(params[:id])
    @teacher.destroy
    redirect_to teachers_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student Managment</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <!--	 <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.15.0/font/bootstrap-icons.css" rel="stylesheet">-->
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand " href="">DH</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-active">
            <a class="nav-link active" aria-current="page" href="<%= homes_index_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= students_path %>">Students</a>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=sections_path %>">Sections</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= teachers_path%>">Teachers</a>
          </li>
        </ul>

        <form class="d-flex" method="GET" action="<%= search1_students_path %>">
          <input class="form-control me-2" type="text" name="query" placeholder="Search ">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>

    </div>
  </nav>
    <div class="">
    <%= yield %>
    </div>
    <!-- Add the Bootstrap JavaScript, Popper.js, and jQuery -->
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.12.0/dist/umd/popper.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/sections/edit.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="container my-4 h-3 d-flex justify-content-center text-dark-emphasis  border-b  border-danger-subtle ">
 Update Student
</div>
  <div class="container border border-info my-4 shadow p-3 mb-5 bg-danger-subtle  ">
    <div class="d-flex  justify-content-end">
      <%= link_to  sections_path,  class: "btn btn-outline-primary " do %>
        <i class="bi bi-x"></i>
      <% end %>
    </div>

    <%= form_with(model: @section,url: section_path(@section), :method => 'patch', local: true) do |f| %>
        <div class="col">
          <%= f.label :section_name %><br>
          <%= f.text_field :name, required: true, class: 'form-select border-danger' %>
        </div>
        <div class="col">
          <%= f.label :student_range %><br>
          <%= f.number_field :student_range, in: 1..60, required: true, class: 'form-select border-danger' %>
        </div>
        <div class="col">
          <%= f.label :student_id, 'choose Student' %>
          <%= f.collection_select :student_id, Student.all, :id, :name, { prompt: 'Select student_name' }, { class: 'form-select border-danger' } %>
        </div>
        <br>
        <div class="d-flex justify-content-center">
          <%= f.submit ('update student'), class: "btn btn-outline-danger  col-3 max-auto " %>
        </div>
<% end %><br>
  </div>

app/views/sections/index.html.erb
<div class=" d-flex justify-content-end me-2 my-4">
	<form class="d-flex" method="GET" action="<%= search_sections_path %>">
		<input class="form-control me-2" type="text" name="query" placeholder="Search Sections ">
		<button class="btn btn-outline-danger" type="submit">Search</button>
	</form>
</div>
<div class=" d-flex justify-content-end my-4">
	<div  class="container  h3 d-flex justify-content-center text-danger-emphasis border-bottom border-danger ">
		Section Index
	</div>
 <span>
	 		<meta name="viewport" content="width=device-width, initial-scale=1">
			<%= link_to "Create Section ", new_section_path, class: "btn btn btn-outline-dark me-2 shadow  border border-4 border-danger-subtle bg-danger-subtle " %>
	 <!--bootstrap icons CDN Add-->
<!--	 <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.15.0/font/bootstrap-icons.css" rel="stylesheet">-->
 </span>
</div>

<div class="  table-responsive-sm my-4 ">
<table class="table align-middle  border border-4  shadow p-3 mb-5 border-danger-subtle ">
	<thead class="table-dark ">
		<tr>
			<th scope="col" >ID</th>
    		<th scope="col">Sections </th>
    		<th scope="col">Students Range</th>
    		<th scope="col">Total students</th>
<!--			<th scope="col">students name</th>-->
			<th scope="col">Show</th>
    		<th scope="col">Edit</th>	
    		<th scope="col">Delete</th>
  		</tr>
  	</thead>
  	<tbody>	

  	<% @sections.each do |section|%>
  		<tr>
    		<td class="text-primary-emphasis"><%= section.id %></td>
    		<td ><%= section.name %></td>	
    		<td> 
          <% if section.student_range.present? && section.student_range <= 60 %>
						<%= section.student_range %>
            <%#= section.students.name %>
            <% else %>
            <script>
              alert("Error: Student range must be less than or equal to 60.");
            </script>
            Maximum limit exceeded
            <% end %>
				</td>
    		<td><%= section.students.count %></td>

<!--				<td>-->
					<%# section.students.each do |student| %>
<!--						ID: <%#= section.id %>, Name: <%#= student.name %><br>-->
<!--						<div class=" border-bottom border-danger-subtle">-->
<!--						<%#= section.id %>,<%#= student.name %>-->
<!--						</div>-->
					<%# end %>
<!--				</td>-->
				<!-- index -->
				<td class="action">
					<!-- <= link_to("Show", '/students', :class => 'action show' ) %> -->
					<%= link_to(section_path(section), class: "btn btn-outline-success") do %>
						<i class="bi bi-eye-fill"></i>
					<% end %>
					<td class="action">
						<%#= link_to("Edit", edit_student_path(student),:data => { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn btn-outline-info bi bi-pencil"  ) %>
						<%= link_to(edit_section_path(section), data: { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn-outline-primary") do %>
							<i class="bi bi-pencil-fill "></i>
						<%end%>
					</td>
					<td class="action">
						<%#= button_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn btn-outline-danger', form: { class: 'd-inline' } %>
						<%= button_to section_path(section), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn-outline-danger d-inline' do %>
							<i class="bi bi-trash-fill"></i>
						<% end %>
					</td>
  		</tr>
 	<% end %>
	</tbody>
</table>
</div>

app/views/sections/new.html.erb
<div  class="container my-4 h3 d-flex justify-content-center text-dark-emphasis border-bottom border-danger-subtle ">
 New Section
</div>

<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="container border border-info my-4 shadow p-3 mb-5 bg-danger-subtle  ">
  <div class="d-flex justify-content-end">
    <!-- 1st way   <button class="btn btn-outline-primary" onclick="location.href='<%= sections_path %>'" role="button"> Back to list </button>-->
    <!-- 2nd way <= link_to("Back to list", '/sections/index', :class => 'back link' ) %> -->
    <!-- 3rd way-->
    <%= link_to  sections_path,  class: "btn btn-outline-primary " do %>
      <i class="bi bi-x"></i>
    <% end %>
  </div>

<%= form_with :url => sections_path, :method => 'post', local: true do |f| %>
   <div class="col">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, class: 'form-select border-danger' %>
  </div>
  <div class="col">
    <%= f.label :student_range %><br>
      <%= f.number_field :student_range, in: 1..60,required: true, class: 'form-select border-danger' %><!-- Set the range limit for the student_range field -->
  </div>
  <!-- <p>
    <= f.label :student_count%><br>
    < = f.number_field :student_count %>
  </p> -->
<!--  <div class="col">-->
<!--    <%#= f.label :choice_students%><br>-->
    <%#= f.select :student_id, options_for_select(Student.all.map { |s| [s.id] }), class: 'form-select border-success' %>
<!--  </div>-->
  <div class="col">
    <%= f.label :student_id, 'choose Student' %>
    <%= f.collection_select :student_id, Student.all, :id, :name, { prompt: 'Select student_name' }, { class: 'form-select border-danger' } %>
  </div><br>
  <div class="form-button">
    <%= f.submit ('create section'), class: 'btn btn-outline-danger d-grid gap-2 col-3 mx-auto' %>
  </div>
<% end %>
</div>

app/views/sections/show.html.erb
<div class=" my-3 d-flex justify-content-center border-bottom  border-danger-subtle h3">
	Sections show
</div>
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class=" container justify-content-canter bg-danger-subtle align-middle  border border-4  shadow p-3 mb-5 border border-danger my-4 ">
		<div class="d-flex my-2  justify-content-end">
			<%= link_to  sections_path,  class: "btn btn-outline-primary" do %>
				<i class="bi bi-x"></i>
			<% end %>
		</div>
<table class="container align-middle " >
	<tr class="border-bottom border-danger-subtle">
		<th>Name</th>
		<td><%= @section.name %></td>
	</tr>
	<tr class="border-bottom border-danger-subtle">
		<th>Student Range</th>
		<td><%= @section.student_range %></td>
	</tr>
	<tr>
		<th>Total Student in Section </th>
		<td><%= @section.students.count %></td>
	</tr>
</table>
</div>
<div class=" my-3 d-flex justify-content-center border-bottom  border-danger-subtle h3">
	Sections Students  show
</div>
<br>
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class=" container justify-content-canter bg-danger-subtle align-middle  border border-4  shadow p-3 mb-5 border border-danger my-4 ">
	<div class="d-flex my-2  justify-content-end">
		<%= link_to  sections_path,  class: "btn btn-outline-primary" do %>
			<i class="bi bi-x"></i>
		<% end %>
	</div>
	<table class="container align-middle " >
		<tr class="border-bottom border-danger-subtle">
			<th>Name</th>
			<td><%= @section.name %></td>
		</tr>
		<tr class="border-bottom border-danger-subtle">
			<th>Students Name</th>
			<td>
				<% @section.students.each do |student| %>
					<%=@section.id %> <%= student.name %><br><!--according to section get students recode exist in sections-->
				<% end %>
			</td>
		</tr>

		<%# @section.each do |section|%>
<!--		<tr>-->
<!--			<th>Total Student in Section </th>-->
<!--			<td><%#= section.students.name %></td>-->
<!--		</tr>-->

		<%# end %>

	</table>
</div>

app/views/students/index.html.erb
<div class=" d-flex justify-content-end me-2 my-4">
	<form class="d-flex" method="GET" action="<%= search_students_path %>">
		<input class="form-control me-2" type="text" name="query" placeholder="Search Students ">
		<button class="btn btn-outline-info" type="submit">Search</button>
	</form>
</div>
<meta name="viewport" content="width=device-width, initial-scale=1">
<div class="d-flex justify-content-end my-4">
	<div  class="container  h3 d-flex justify-content-center  border-bottom border-primary-subtle ">
		Student Index
	</div>


	<span>
		<%= link_to "Create Student", new_student_path, class: "btn btn-outline-dark me-2 shadow  border border-4 border-info-subtle bg-info-subtle" %>
  </span>
</div>

<div class="table-responsive-sm my-4">

<table class="table align-middle  border border-5  shadow p-3 mb-5 border-primary-subtle ">
	<thead class="table-dark ">
		<tr>
  			<th scope="col" >ID</th>
    		<th scope="col" >Name</th>
   			<th scope="col" >Age</th>
    		<th scope="col" >Father</th>
   			<th scope="col" >Phone_number</th>
    		<th scope="col" >Email</th>
        <th scope="col" >Guardian</th>
        <th scope="col" >date_of_birth</th>
        <th scope="col" >Gender</th>
    		<th scope="col" >Blood_group</th>
    		<th scope="col" >Section</th>
    		<th scope="col" >Show</th>
   			<th scope="col" >Edit</th>
    		<th scope="col" >Delete</th>
  		</tr>
  	</thead>
  	<tbody>
  		<% @students.each do |student|%>
  			<tr>
  				<td class="text-secondary"><%= student.id %></td>
    			<td><%= student.name %></td>
    			<td><% if student.age <= 60 %>
            <%= student.age %>
            <% else %>
            <script>
              alert("Error: Student range must be less than or equal to 60.");
            </script>
            Maximum limit exceeded
            <% end %>
          </td>
    			<td><%= student.father_name %></td>
    			<td>
            <% if student.phone_number.present? %>
              <% student_phone_number = "#{student.phone_number[0..3]}- #{student.phone_number[4..10]}" %>
              <%= student_phone_number %>
             <% else %>
              No phone number provided
            <% end %>
          </td>
   				<td><%= student.email %></td>
          <td><%= student.guardian_no %></td>
          <td><%= student.date_of_birth&.strftime('%d-%m-%Y') %></td>
          <td><%= student.gender %></td>
    			<td><% if /(A\+|A\-|B\+|B\-|AB\+|AB\-|O\+|O\-)/.match?(student.blood_group) %>
            <%= student.blood_group %>
            <% else %>
            <script>
              alert("enter a correct blood group like A+")
            </script>
            invalid blood group
            <% end %>
            </td>

					<td>
						<%=  student.section.name %>
					</td>
    			<td class="action">
    			<!-- <= link_to("Show", '/students', :class => 'action show' ) %> -->
						<%= link_to(student_path(student), class: "btn btn-outline-primary") do %>
							<i class="bi bi-eye"></i>
						<% end %>
    			<td class="action">
						<%#= link_to("Edit", edit_student_path(student),:data => { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn btn-outline-info bi bi-pencil"  ) %>
						<%= link_to(edit_student_path(student), data: { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn-outline-info") do %>
							<i class="bi bi-pencil"></i>
						<%end%>
					</td>
          <td class="action">
            <%#= button_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn btn-outline-danger', form: { class: 'd-inline' } %>
						<%#= button_to student_path(student), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn-outline-danger d-inline' do %>
<!--							<i class="bi bi-trash"></i>-->
						<%# end %>
						<%= button_to student_path(student), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn-outline-danger d-inline' do %>
							<i class="bi bi-trash"></i> Delete
						<% end %>


					</td>
  			</tr>
  	<% end %>
	</tbody>
</table>
</div>

app/views/teachers/index.html.erb
<div class=" d-flex justify-content-end me-2 my-4">
	<form class="d-flex" method="GET" action="<%= search_teachers_path %>">
		<input class="form-control me-2" type="text" name="query" placeholder="Search Teachers ">
		<button class="btn btn-outline-warning" type="submit">Search</button>
	</form>
</div>
<meta name="viewport" content="width=device-width, initial-scale=1">
	<div class="d-flex justify-content-end my-4">
<div class="container  h3 d-flex justify-content-center text-hover border-bottom border-warning ">
	Teacher index
</div>

	<div class=" my-2 me-3 d-flex justify-content-end">
		<span>
    <%= link_to "Create Teacher ", new_teacher_path, class: "btn btn btn-outline-success border-warning" %>
		</span>
	</div>

<!--	<span>-->
		<%#= link_to "Create Student", new_teacher_path, class: "btn btn-outline-success" %>
<!--  </span>-->
	</div>

<!-- <style>
  .table td{
    padding-right: 2px; /* Adjust the desired amount of space */
  }
  .table th {
    padding-right: 10px; /* Adjust the desired amount of space */
  }
  table, th, td {
  border: 2px solid black;
  border-collapse: collapse;
</style>
 -->
		<div class=" table-responsive-sm my-4 ">
		<table class="table align-middle  border border-4  shadow p-3 mb-5 border-warning-subtle   ">
<thead class="table-dark ">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Phone</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Date of Birth</th>
		<th>Address</th>
		<th>Qualifications</th>		
		<th>Subject</th>
		<th scope="col">Show</th>
    <th scope="col">Edit</th>	
    <th scope="col">Delete</th>
	</tr>
</thead>
<tbody>
	  	<% @teachers.each do |teacher|%>
	  	<tr>
	  		<td><%= teacher.id  %></td>
    		<td><%= teacher.name %></td>    		
    		<td><%= teacher.phone_number %></td>
    		<td><%= teacher.email %></td>
    		<td><%= teacher.gender %></td>
    		<td><%= teacher.date_of_birth %></td>
    		<td><%= teacher.address %></td>
    		<td><%= teacher.qualification %></td>
    		<td><%= teacher.subject %></td>

				<td class="action">
					<!-- <= link_to("Show", '/students', :class => 'action show' ) %> -->
					<%= link_to(teacher_path(teacher), class: "btn btn-outline-success") do %>
						<i class="bi bi-eye-fill"></i>
					<% end %>
					<td class="action">
						<%#= link_to("Edit", edit_student_path(student),:data => { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn btn-outline-info bi bi-pencil"  ) %>
						<%= link_to(edit_teacher_path(teacher), data: { confirm: "Are you sure you want to Edit this student?" }, class: "btn btn-outline-primary") do %>
							<i class="bi bi-pencil-fill "></i>
						<%end%>
					</td>
					<td class="action">
						<%#= button_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn btn-outline-danger', form: { class: 'd-inline' } %>
						<%= button_to teacher_path(teacher), method: :delete, data: { confirm: 'Are you sure you want to delete this student?' }, class: 'btn btn-outline-danger d-inline' do %>
							<i class="bi bi-trash-fill"></i>
						<% end %>
					</td>

	  	</tr>
		<%end%>
</tbody>
</table>
</div>